### ISSUE TITLE
No result for the polished pumpkin bread stairs crafting recipe

### ISSUE THREAD

**Issue by haykam821** [Evoslab/Breadcrumbs-Fabric#4]
The recipe with the identifier `breadcrumbs:crafting/polished_pumpkin_bread_stairs` does not specify a `result`, meaning the recipe is invalid:

```
[main/ERROR] (Minecraft) Parsing error loading recipe breadcrumbs:crafting/polished_pumpkin_bread_stairs
com.google.gson.JsonSyntaxException: Missing result, expected to find a JsonObject
```

**Comment by StevePlayzz** [comment]
Sorry for not responding later but the pumpkin and honey version are being deleted from breadcrumbs since they were actually compact for another mod that's not on fabric.
